version: "3.8"
services:
  backend:
    image: yourdockerhub/enterprise-backend:latest   # Jenkins will push here
    container_name: ep_backend
    restart: unless-stopped
    ports:
      - "3001:3001"

  frontend:
    image: yourdockerhub/enterprise-frontend:latest
    container_name: ep_frontend
    restart: unless-stopped
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    container_name: ep_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
